"use client";

import { ArrowDown, ArrowRight, ArrowUp, BusFront, Clock3, Lightbulb, MapPin, Pencil, StickyNote, Trash2 } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { TimePicker } from "@/components/date-time/time-picker";
import { StatusPill } from "@/components/ui/status-pill";
import type { ItineraryDayRow, ItineraryItemRow, ItineraryItemType, TripPlaceRow } from "@/lib/supabase/database.types";
import { moveItineraryItem, moveItineraryItemToDay, removeItineraryItem, updateItineraryItem } from "./item-actions";

const control = "mt-2 h-10 w-full rounded-xl border border-input bg-background/55 px-3 text-sm text-foreground outline-none transition focus:border-primary/55 focus:ring-3 focus:ring-primary/15";
const labels = { activity:"Aktivita", transport:"Přesun", note:"Poznámka" } as const;
const icons = { activity:Lightbulb, transport:BusFront, note:StickyNote } as const;
const dayDateFormatter = new Intl.DateTimeFormat("cs-CZ", { day: "numeric", month: "short", year: "numeric", timeZone: "UTC" });

export function DayTimeline({ canEdit, dayId, days, items, onSelectItem, places, selectedItemId, tripId }: { canEdit:boolean; dayId:string; days:ItineraryDayRow[]; items:ItineraryItemRow[]; onSelectItem?:(itemId:string)=>void; places:TripPlaceRow[]; selectedItemId?:string|null; tripId:string }) {
  const targetDays = days.filter((day) => day.id !== dayId).toSorted(compareDays);
  const selectItem = onSelectItem ?? (() => {});
  return <div className="grid gap-4">
    {items.length === 0 ? <div className="rounded-2xl border border-dashed border-border p-6 text-center"><Clock3 className="mx-auto size-7 text-primary"/><p className="mt-3 font-medium">Timeline je zatím prázdná</p><p className="mt-1 text-sm leading-6 text-muted-foreground">Přidejte první aktivitu, přesun nebo poznámku.</p></div> : null}
    <ol className="grid gap-3">{items.map((item,index)=><TimelineItem key={item.id} canEdit={canEdit} dayId={dayId} index={index} item={item} onSelectItem={selectItem} places={places} selected={selectedItemId===item.id} targetDays={targetDays} total={items.length} tripId={tripId}/>)}</ol>
  </div>;
}

function TimelineItem({ canEdit, dayId, index, item, onSelectItem, places, selected, targetDays, total, tripId }: { canEdit:boolean; dayId:string; index:number; item:ItineraryItemRow; onSelectItem: (itemId:string)=>void; places:TripPlaceRow[]; selected:boolean; targetDays:ItineraryDayRow[]; total:number; tripId:string }) {
  const Icon = icons[item.item_type]; const time = [formatTime(item.start_time),formatTime(item.end_time)].filter(Boolean).join("–");
  const place = item.place_id ? places.find((candidate) => candidate.id === item.place_id) : null;
  const [expanded, setExpanded] = useState<"edit"|"move"|null>(null);
  const toggle = (next:"edit"|"move") => setExpanded((current) => current === next ? null : next);
  return <li id={`timeline-item-${item.id}`} data-selected={selected} className={`group relative scroll-mt-6 rounded-2xl border bg-muted/22 p-3 transition-[background-color,border-color,box-shadow] duration-200 hover:border-primary/35 hover:bg-muted/40 focus-within:border-primary/35 focus-within:bg-muted/40 sm:ml-5 ${selected ? "border-primary/60 bg-primary/8 shadow-[0_12px_28px_-24px_var(--brand-glow)]" : "border-border"}`}><span className="absolute top-6 -left-[1.7rem] hidden size-3 rounded-full border-2 border-primary bg-background shadow-[0_0_12px_var(--brand-glow)] sm:block"/>
    <button type="button" aria-label={`Vybrat ${item.title} na mapě`} aria-pressed={selected} onClick={() => onSelectItem(item.id)} className="flex w-full items-start gap-3 rounded-xl p-1 text-left outline-none focus-visible:ring-2 focus-visible:ring-primary/60">
      <span className="grid size-9 shrink-0 place-items-center rounded-xl bg-primary/12 text-primary"><Icon className="size-4.5"/></span><span className="min-w-0 flex-1"><span className="flex flex-wrap items-center gap-2"><span className="font-medium">{item.title}</span><StatusPill tone={item.item_type === "transport" ? "warning" : item.item_type === "activity" ? "brand" : "neutral"}>{labels[item.item_type]}</StatusPill></span><span className="mt-1 block text-xs text-muted-foreground">{time || "Bez přesného času"}</span>{place?<span className="mt-2 flex items-center gap-1.5 text-xs text-[var(--brand-highlight)]"><MapPin className="size-3.5"/>{place.name}{place.city?` · ${place.city}`:""}</span>:null}{item.notes ? <span className="mt-2 block whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{item.notes}</span> : null}</span>
    </button>
    {canEdit ? <div className="mt-2 flex items-center justify-between gap-2"><div className="flex items-center gap-1"><Move dayId={dayId} direction="up" disabled={index===0} itemId={item.id} tripId={tripId}/><Move dayId={dayId} direction="down" disabled={index===total-1} itemId={item.id} tripId={tripId}/></div><div className="flex items-center gap-1 transition-opacity duration-150 md:opacity-0 md:group-hover:opacity-100 md:group-focus-within:opacity-100">{targetDays.length > 0 ? <IconAction expanded={expanded === "move"} icon={<ArrowRight/>} label="Přesunout do jiného dne" onClick={() => toggle("move")}/>:null}<IconAction expanded={expanded === "edit"} icon={<Pencil/>} label="Upravit bod" onClick={() => toggle("edit")}/></div></div> : null}
    {expanded === "move" ? <MoveToDay dayId={dayId} itemId={item.id} targetDays={targetDays} tripId={tripId}/> : null}
    {expanded === "edit" ? <EditItem dayId={dayId} item={item} places={places} tripId={tripId}/> : null}
  </li>;
}

function IconAction({ expanded, icon, label, onClick }: { expanded:boolean; icon:React.ReactNode; label:string; onClick:()=>void }) { return <Button type="button" variant="ghost" size="icon-sm" aria-expanded={expanded} aria-label={label} title={label} onClick={onClick} className="min-h-10 min-w-10 text-muted-foreground hover:text-primary">{icon}</Button>; }

function EditItem({ dayId, item, places, tripId }: { dayId:string; item:ItineraryItemRow; places:TripPlaceRow[]; tripId:string }) { return <div className="mt-3 rounded-xl border border-border bg-background/25 p-3"><form action={updateItineraryItem} className="grid gap-4 sm:grid-cols-2"><Ids dayId={dayId} itemId={item.id} tripId={tripId}/><Fields item={item} places={places}/><Button type="submit" size="lg" className="sm:col-span-2 sm:justify-self-start">Uložit bod</Button></form><div className="mt-4 border-t border-border pt-4"><p className="text-xs text-muted-foreground">Odstranění tohoto bodu je trvalé.</p><form action={removeItineraryItem} className="mt-2"><Ids dayId={dayId} itemId={item.id} tripId={tripId}/><Button type="submit" variant="destructive"><Trash2/> Ano, odstranit bod</Button></form></div></div>; }

function MoveToDay({ dayId, itemId, targetDays, tripId }: { dayId:string; itemId:string; targetDays:ItineraryDayRow[]; tripId:string }) { return <div className="mt-3 min-w-0 rounded-xl border border-border bg-background/25 p-3"><form action={moveItineraryItemToDay} className="grid min-w-0 gap-3 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-end"><Ids dayId={dayId} itemId={itemId} tripId={tripId}/><label className="min-w-0 text-xs font-medium text-muted-foreground">Cílový den<select className={`${control} min-w-0`} name="targetDayId" required>{targetDays.map((day) => <option key={day.id} value={day.id}>{formatDayOption(day)}</option>)}</select></label><Button type="submit" variant="outline" className="w-full sm:w-auto"><ArrowRight/> Přesunout</Button></form></div>; }
function Move({ dayId, direction, disabled, itemId, tripId }: { dayId:string; direction:"up"|"down"; disabled:boolean; itemId:string; tripId:string }) { const Icon=direction==="up"?ArrowUp:ArrowDown; const label=direction==="up"?"Posunout bod nahoru":"Posunout bod dolů"; return <form action={moveItineraryItem}><Ids dayId={dayId} itemId={itemId} tripId={tripId}/><input type="hidden" name="direction" value={direction}/><Button type="submit" variant="ghost" size="icon-sm" disabled={disabled} aria-label={label} title={label} className="min-h-10 min-w-10 text-muted-foreground hover:text-primary"><Icon/></Button></form>; }
function Ids({ dayId, itemId, tripId }: { dayId:string; itemId?:string; tripId:string }) { return <><input type="hidden" name="tripId" value={tripId}/><input type="hidden" name="dayId" value={dayId}/>{itemId?<input type="hidden" name="itemId" value={itemId}/>:null}</>; }
function Fields({ item, places }: { item?:ItineraryItemRow; places:TripPlaceRow[] }) { return <><label className="text-xs font-medium text-muted-foreground">Typ<select className={control} name="type" defaultValue={item?.item_type??"activity"}>{(Object.keys(labels) as ItineraryItemType[]).map(type=><option key={type} value={type}>{labels[type]}</option>)}</select></label><label className="text-xs font-medium text-muted-foreground">Název<input className={control} name="title" defaultValue={item?.title??""} maxLength={160} placeholder="Návštěva chrámu" required/></label><label className="text-xs font-medium text-muted-foreground sm:col-span-2">Uložené místo (volitelné)<select className={control} name="placeId" defaultValue={item?.place_id??""}><option value="">Bez propojeného místa</option>{places.map(place=><option key={place.id} value={place.id}>{place.name}{place.city?` · ${place.city}`:""}</option>)}</select></label><TimePicker label="Začátek (volitelný)" name="startTime" defaultValue={formatTime(item?.start_time)}/><TimePicker label="Konec (volitelný)" name="endTime" defaultValue={formatTime(item?.end_time)}/><label className="text-xs font-medium text-muted-foreground sm:col-span-2">Poznámka<textarea className={`${control} h-24 py-3`} name="notes" defaultValue={item?.notes??""} maxLength={1200} placeholder="Praktické informace, adresa nebo připomínka"/></label></>; }
function formatTime(value:string|null|undefined) { return value?.slice(0,5) ?? ""; }
function compareDays(left: ItineraryDayRow, right: ItineraryDayRow) { if (left.day_date && right.day_date) return left.day_date.localeCompare(right.day_date) || left.name.localeCompare(right.name, "cs"); if (left.day_date) return -1; if (right.day_date) return 1; return (left.sort_order ?? 0) - (right.sort_order ?? 0) || left.name.localeCompare(right.name, "cs"); }
function formatDayOption(day: ItineraryDayRow) { if (!day.day_date) return `Plán bez data · ${day.name}`; const date = dayDateFormatter.format(new Date(`${day.day_date}T00:00:00Z`)); return `${date} · ${day.name}`; }
