"use server";
import{revalidatePath}from"next/cache";import{redirect}from"next/navigation";import{createClient}from"@/lib/supabase/server";import{parsePlace}from"./place-input";
import{parseMapboxPlace}from"./mapbox-place-input";
const uuidPattern=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function path(tripId:string,status:string){return uuidPattern.test(tripId)?`/app/trips/${tripId}/itinerary?place=${status}`:"/app/trips"}async function client(tripId:string){const supabase=await createClient();const{data}=await supabase.auth.getUser();if(!data.user)redirect(`/login?next=/app/trips/${tripId}/itinerary`);return supabase}function refresh(tripId:string){revalidatePath(`/app/trips/${tripId}/itinerary`);revalidatePath(`/app/trips/${tripId}/itinerary/[dayId]`,"page")}
function args(value:ReturnType<typeof parsePlace>){if(!value.success)throw new Error("Invalid parsed place");return{place_address:value.data.address,place_category:value.data.category,place_city:value.data.city,place_country_code:value.data.countryCode,place_latitude:value.data.latitude,place_longitude:value.data.longitude,place_name:value.data.name}}
export async function createTripPlace(formData:FormData){const tripId=formData.get("tripId")?.toString().trim()??"";const parsed=parsePlace(formData);if(!uuidPattern.test(tripId)||!parsed.success)redirect(path(tripId,parsed.success?"invalid":parsed.error));const supabase=await client(tripId);const{data,error}=await supabase.rpc("create_manual_trip_place",{target_trip_id:tripId,...args(parsed)});if(error||!data)redirect(path(tripId,"error"));refresh(tripId);redirect(path(tripId,"created"))}
export async function createMapboxTripPlace(formData:FormData){const tripId=formData.get("tripId")?.toString().trim()??"";const parsed=parseMapboxPlace(formData);if(!uuidPattern.test(tripId)||!parsed.success)redirect(path(tripId,"mapbox-invalid"));const supabase=await client(tripId);const{data,error}=await supabase.rpc("create_mapbox_trip_place",{target_trip_id:tripId,source_provider_place_id:parsed.data.providerPlaceId,place_name:parsed.data.name,place_address:parsed.data.address,place_country_code:parsed.data.countryCode,place_city:parsed.data.city,place_latitude:parsed.data.latitude,place_longitude:parsed.data.longitude,place_provider_category:parsed.data.providerCategory,place_category:parsed.data.category});if(error||!data)redirect(path(tripId,"mapbox-error"));refresh(tripId);redirect(path(tripId,"mapbox-saved"))}
export async function updateTripPlace(formData:FormData){const tripId=formData.get("tripId")?.toString().trim()??"";const placeId=formData.get("placeId")?.toString().trim()??"";const parsed=parsePlace(formData);if(!uuidPattern.test(tripId)||!uuidPattern.test(placeId)||!parsed.success)redirect(path(tripId,parsed.success?"invalid":parsed.error));const supabase=await client(tripId);const{data,error}=await supabase.rpc("update_manual_trip_place",{target_place_id:placeId,...args(parsed)});if(error||data!=="updated")redirect(path(tripId,"error"));refresh(tripId);redirect(path(tripId,"updated"))}
export async function removeTripPlace(formData:FormData){const tripId=formData.get("tripId")?.toString().trim()??"";const placeId=formData.get("placeId")?.toString().trim()??"";if(!uuidPattern.test(tripId)||!uuidPattern.test(placeId))redirect(path(tripId,"invalid"));const supabase=await client(tripId);const{data,error}=await supabase.rpc("remove_trip_place",{target_place_id:placeId});if(error||!data)redirect(path(tripId,"error"));if(data==="in_use")redirect(path(tripId,"in-use"));refresh(tripId);redirect(path(tripId,"removed"))}
