import { AlertTriangle, BedDouble, CalendarDays, CheckSquare2, ChevronRight, CircleDollarSign, FileText, Luggage, Map, Plane, ReceiptText } from "lucide-react";
import Link from "next/link";
import { formatBudgetMoney } from "@/features/budget/budget-model";
import type { getTripOverviewData } from "./overview-data";
import { Surface } from "@/components/ui/surface";

type Overview = Awaited<ReturnType<typeof getTripOverviewData>>;
export function TripOverviewDashboard({ data, tripId }: { data: Overview; tripId: string }) {
  const financeHref = `/app/trips/${tripId}/budget`; const itineraryHref = `/app/trips/${tripId}/itinerary`; const accommodationHref = `/app/trips/${tripId}/accommodation`;
  return <div className="mt-5 min-w-0 space-y-5">
    <section aria-label="Stav cesty" className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">
      <Summary href={financeHref} icon={<CircleDollarSign />} title="Rozpočet">{data.currencies.length ? data.currencies.map((row) => <p key={row.currency} className="text-xs"><strong className="text-sm text-foreground">{formatBudgetMoney(row.actual + row.estimated, row.currency)}</strong><span className="block text-muted-foreground">zaplaceno {formatBudgetMoney(row.paid, row.currency)} · zbývá {formatBudgetMoney(row.remaining, row.currency)}</span></p>) : <Empty>Bez evidovaných nákladů.</Empty>}</Summary>
      <Summary href={accommodationHref} icon={<BedDouble />} title="Ubytování"><strong>{Math.max(0, data.accommodation.nights - data.coverage.gapNights)} / {data.accommodation.nights || "–"} nocí</strong><p className="text-xs text-muted-foreground">{data.coverage.gapNights ? `Chybí ${data.coverage.gapNights} nocí` : `${data.accommodation.reservations} rezervace`}</p></Summary>
      <Summary href={itineraryHref} icon={<CalendarDays />} title="Itinerář"><strong>{data.itinerary.plannedDays} / {data.itinerary.totalDays} dní naplánováno</strong><p className="text-xs text-muted-foreground">{data.itinerary.items} bodů v itineráři</p></Summary>
      <Summary href={`/app/trips/${tripId}/checklist`} icon={<CheckSquare2 />} title="Příprava"><strong>Úkoly {data.task.completed} / {data.task.total}</strong><p className="text-xs text-muted-foreground">Balení {data.packing.packed} / {data.packing.total}</p></Summary>
    </section>
    <Attention alerts={data.alerts} />
    <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1.55fr)_minmax(18rem,0.85fr)]">
      <div className="space-y-5">
        <Block href={data.selectedDay ? `${itineraryHref}/${data.selectedDay.id}` : itineraryHref} icon={<CalendarDays />} title={data.selectedDay ? data.selectedDay.name : "Itinerář"} action="Celý itinerář"><p className="text-sm text-muted-foreground">{data.selectedDay?.day_date ?? "Zatím není naplánovaný žádný den."}</p>{data.dayItems.map((item) => <p key={item.id} className="mt-2 text-sm"><span className="mr-2 text-muted-foreground">{item.start_time ?? "—"}</span>{item.title}</p>)}</Block>
        <div className="grid gap-5 md:grid-cols-2"><Transport data={data} tripId={tripId} /><Accommodation data={data} tripId={tripId} /></div>
      </div>
      <aside className="space-y-5"><Payment data={data} tripId={tripId} /><Tasks data={data} tripId={tripId} /><Documents data={data} tripId={tripId} /><Block href={`/app/trips/${tripId}/map`} icon={<Map />} title="Mapa" action="Otevřít mapu"><p className="text-sm text-muted-foreground">Místa a body cesty otevřete v mapovém modulu.</p></Block></aside>
    </div>
  </div>;
}
function Summary({ children, href, icon, title }: { children: React.ReactNode; href: string; icon: React.ReactNode; title: string }) { return <Link href={href} className="min-w-0 rounded-2xl border border-border bg-card/60 p-3.5 transition hover:border-primary/35"><div className="mb-2 flex items-center gap-2 text-sm font-medium"><span className="text-primary">{icon}</span>{title}</div>{children}</Link>; }
function Block({ action, children, href, icon, title }: { action: string; children: React.ReactNode; href: string; icon: React.ReactNode; title: string }) { return <Surface depth="panel" className="min-w-0 p-4"><div className="flex items-center justify-between gap-3"><h2 className="flex min-w-0 items-center gap-2 text-base font-semibold"><span className="text-primary">{icon}</span><span className="truncate">{title}</span></h2><Link href={href} className="inline-flex shrink-0 items-center gap-1 text-xs text-[var(--brand-highlight)]">{action}<ChevronRight className="size-3" /></Link></div><div className="mt-3">{children}</div></Surface>; }
function Attention({ alerts }: { alerts: Overview["alerts"] }) { return <Surface depth="panel" className="p-4"><div className="flex items-center gap-2"><AlertTriangle className={alerts.length ? "size-4 text-amber-300" : "size-4 text-emerald-300"} /><h2 className="font-semibold">Vyžaduje pozornost{alerts.length ? ` · ${alerts.length}` : ""}</h2></div>{alerts.length ? <div className="mt-3 grid gap-2 md:grid-cols-2">{alerts.map((alert) => <Link key={alert.id} href={alert.href} className="rounded-xl border border-amber-400/15 bg-amber-400/5 p-3 text-sm"><strong>{alert.title}</strong><span className="mt-1 block text-xs text-muted-foreground">{alert.detail}</span></Link>)}</div> : <p className="mt-2 text-sm text-muted-foreground">Vše důležité je připravené.</p>}</Surface>; }
function Payment({ data, tripId }: { data: Overview; tripId: string }) { const item = data.nearestPayment; return <Block href={item?.href ?? `/app/trips/${tripId}/budget`} icon={<ReceiptText />} title="Nejbližší platba" action="Rozpočet">{item ? <><p className="font-medium">{item.name}</p><p className="mt-1 text-sm text-muted-foreground">{formatBudgetMoney(item.remainingAmount ?? 0, item.currency)} · {item.balanceDueDate ? `splatnost ${item.balanceDueDate}` : "bez termínu"}</p></> : <Empty>Žádná naplánovaná platba.</Empty>}</Block>; }
function Transport({ data, tripId }: { data: Overview; tripId: string }) { const item = data.nearestTransport; return <Block href={`/app/trips/${tripId}/transport`} icon={<Plane />} title="Nejbližší přesun" action="Doprava">{item ? <><p className="font-medium">{item.booking.title}{item.segment.service_number ? ` · ${item.segment.service_number}` : ""}</p><p className="mt-1 text-sm text-muted-foreground">{item.segment.departurePlace?.name ?? "Odjezd"} → {item.segment.arrivalPlace?.name ?? "Příjezd"}</p><p className="text-xs text-muted-foreground">{item.segment.departure_at ? new Intl.DateTimeFormat("cs-CZ", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.segment.departure_at)) : "Termín není zadaný"}</p></> : <Empty>Zatím žádný budoucí přesun.</Empty>}</Block>; }
function Accommodation({ data, tripId }: { data: Overview; tripId: string }) { const item = data.upcomingAccommodation; return <Block href={`/app/trips/${tripId}/accommodation`} icon={<BedDouble />} title="Ubytování" action="Ubytování">{item ? <><p className="font-medium">{item.name}</p><p className="mt-1 text-sm text-muted-foreground">{item.check_in_date} – {item.check_out_date}{item.check_in_time ? ` · check-in ${item.check_in_time}` : ""}</p></> : <Empty>Zatím není přidané žádné ubytování.</Empty>}</Block>; }
function Tasks({ data, tripId }: { data: Overview; tripId: string }) { return <Block href={`/app/trips/${tripId}/checklist`} icon={<Luggage />} title="Checklist" action="Checklist">{data.openTasks.length ? data.openTasks.map((task) => <p key={task.id} className="border-b border-border py-2 text-sm last:border-0"><span className="font-medium">{task.title}</span>{task.due_date ? <span className="ml-2 text-xs text-muted-foreground">do {task.due_date}</span> : null}</p>) : <Empty>Žádné otevřené úkoly.</Empty>}</Block>; }
function Documents({ data, tripId }: { data: Overview; tripId: string }) { return <Block href={`/app/trips/${tripId}/documents`} icon={<FileText />} title="Dokumenty" action="Dokumenty">{data.document.total ? <p className="text-sm text-muted-foreground">{data.document.total} dokumentů · {data.document.important} důležité · {data.document.offline} označených offline</p> : <Empty>Žádné dokumenty.</Empty>}</Block>; }
function Empty({ children }: { children: React.ReactNode }) { return <p className="text-sm text-muted-foreground">{children}</p>; }
