import { AlertTriangle, BedDouble, CalendarDays, CheckCircle2, CheckSquare2, ChevronRight, CircleDollarSign, FileText, Luggage, Map, Plane, ReceiptText } from "lucide-react";
import Link from "next/link";
import { formatBudgetMoney } from "@/features/budget/budget-model";
import type { getTripOverviewData } from "./overview-data";
import { Surface } from "@/components/ui/surface";
import { formatDateOnly, formatTripDateTime } from "@/lib/date-time";

type Overview = Awaited<ReturnType<typeof getTripOverviewData>>;
export function TripOverviewDashboard({ data, tripId }: { data: Overview; tripId: string }) {
  const financeHref = `/app/trips/${tripId}/budget`; const itineraryHref = `/app/trips/${tripId}/itinerary`; const accommodationHref = `/app/trips/${tripId}/accommodation`;
  return <div className="mt-5 min-w-0 space-y-5">
    <section aria-label="Stav cesty" className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">
      <AttentionSummary alerts={data.alerts} />
      <Summary href={accommodationHref} icon={<BedDouble />} title="Ubytování"><strong>{Math.max(0, data.accommodation.nights - data.coverage.gapNights)} / {data.accommodation.nights || "–"} nocí</strong><p className="text-xs text-muted-foreground">{data.coverage.gapNights ? `Chybí ${data.coverage.gapNights} nocí` : `${data.accommodation.reservations} rezervace`}</p></Summary>
      <Summary href={itineraryHref} icon={<CalendarDays />} title="Itinerář"><strong>{data.itinerary.plannedDays} / {data.itinerary.totalDays} dní naplánováno</strong><p className="text-xs text-muted-foreground">{data.itinerary.items} bodů v itineráři</p></Summary>
      <Summary href={`/app/trips/${tripId}/checklist`} icon={<CheckSquare2 />} title="Příprava"><strong>Úkoly {data.task.completed} / {data.task.total}</strong><p className="text-xs text-muted-foreground">Balení {data.packing.packed} / {data.packing.total}</p></Summary>
    </section>
    <BudgetSummary finance={data.finance} href={financeHref} />
    <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1.55fr)_minmax(18rem,0.85fr)]">
      <div className="space-y-5">
        <Block href={data.selectedDay ? `${itineraryHref}/${data.selectedDay.id}` : itineraryHref} icon={<CalendarDays />} title={data.selectedDay ? data.selectedDay.name : "Itinerář"} action="Celý itinerář"><p className="text-sm text-muted-foreground">{data.selectedDay?.day_date ?? "Zatím není naplánovaný žádný den."}</p>{data.dayItems.map((item) => <p key={item.id} className="mt-2 text-sm"><span className="mr-2 text-muted-foreground">{item.start_time ?? "—"}</span>{item.title}</p>)}</Block>
        <div className="grid gap-5 md:grid-cols-2"><Transport data={data} tripId={tripId} /><Accommodation data={data} tripId={tripId} /></div>
      </div>
      <aside className="space-y-5"><Payment data={data} tripId={tripId} /><Tasks data={data} tripId={tripId} /><Documents data={data} tripId={tripId} /><Block href={`/app/trips/${tripId}/map`} icon={<Map />} title="Mapa" action="Otevřít mapu"><p className="text-sm text-muted-foreground">Místa a body cesty otevřete v mapovém modulu.</p></Block></aside>
    </div>
  </div>;
}
function Summary({ children, href, icon, title }: { children: React.ReactNode; href: string; icon: React.ReactNode; title: string }) { return <Link href={href} className="min-w-0 rounded-2xl border border-border bg-card/60 p-3.5 transition hover:border-primary/35"><div className="mb-2 flex items-center gap-2 text-sm font-medium"><span className="text-primary">{icon}</span>{title}</div>{children}</Link>; }
function Block({ action, children, href, icon, title }: { action: string; children: React.ReactNode; href: string; icon: React.ReactNode; title: string }) { return <Surface depth="panel" className="min-w-0 p-4"><div className="flex items-center justify-between gap-3"><h2 className="flex min-w-0 items-center gap-2 text-base font-semibold"><span className="text-primary">{icon}</span><span className="truncate">{title}</span></h2><Link href={href} className="inline-flex shrink-0 items-center gap-1 text-xs text-[var(--brand-highlight)]">{action}<ChevronRight className="size-3" /></Link></div><div className="mt-3">{children}</div></Surface>; }
function AttentionSummary({ alerts }: { alerts: Overview["alerts"] }) { const first = alerts[0]; const className = "min-w-0 rounded-2xl border border-border bg-card/60 p-3.5 transition hover:border-primary/35"; const content = <><div className="mb-2 flex items-center gap-2 text-sm font-medium"><span className={alerts.length ? "text-amber-300" : "text-emerald-300"}>{alerts.length ? <AlertTriangle /> : <CheckCircle2 />}</span>Vyžaduje pozornost</div>{alerts.length ? <><strong>{alerts.length} {alerts.length === 1 ? "položka" : alerts.length < 5 ? "položky" : "položek"}</strong><p className="mt-1 truncate text-xs text-muted-foreground">{first?.title}{alerts.length > 1 ? ` · +${alerts.length - 1} další` : ""}</p></> : <><strong>Bez upozornění</strong><p className="mt-1 text-xs text-muted-foreground">Vše důležité je připravené.</p></>}</>; return first ? <Link href={first.href} aria-label={`Vyžaduje pozornost, ${alerts.length} položek`} className={className}>{content}</Link> : <div className={className}>{content}</div>; }
function BudgetSummary({ finance, href }: { finance: Overview["finance"]; href: string }) { return <Surface depth="panel" className="min-w-0 p-4 sm:p-5"><div className="flex items-center justify-between gap-3"><h2 className="flex min-w-0 items-center gap-2 text-base font-semibold"><span className="text-primary"><CircleDollarSign /></span><span>Rozpočet</span></h2><Link href={href} className="inline-flex shrink-0 items-center gap-1 text-xs text-[var(--brand-highlight)]">Rozpočet<ChevronRight className="size-3" /></Link></div>{finance.length ? <div className="mt-4 grid gap-5 xl:grid-cols-2">{finance.map((row) => <BudgetCurrency key={row.currency} row={row} />)}</div> : <div className="mt-4 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-muted-foreground">Rozpočet zatím není naplánovaný.</p><p className="mt-1 text-xs text-muted-foreground">Realita bude viditelná po evidenci prvních nákladů.</p></div><Link href={href} className="text-sm font-medium text-[var(--brand-highlight)] hover:underline">Nastavit plán</Link></div>}</Surface>; }
function BudgetCurrency({ row }: { row: Overview["finance"][number] }) { const hasPlan = row.planAmount > 0; const percentage = hasPlan ? Math.round((row.realityAmount / row.planAmount) * 100) : null; const visualPercentage = percentage === null ? 0 : Math.min(percentage, 100); const overBudget = row.remainingBudget < 0; return <div className="min-w-0 rounded-xl border border-border bg-background/25 p-3.5"><div className="flex flex-wrap items-baseline justify-between gap-x-3 gap-y-1"><p className="text-xs font-medium tracking-[0.14em] text-muted-foreground uppercase">{row.currency}</p>{percentage !== null ? <p className={overBudget ? "text-sm font-semibold text-amber-200" : "text-sm font-semibold text-foreground"}>{percentage} %</p> : null}</div><div className="mt-3 grid gap-3 sm:grid-cols-[minmax(0,1.4fr)_minmax(9rem,0.8fr)]"><div><div className="flex flex-wrap items-baseline gap-x-2"><span className="text-sm text-muted-foreground">Realita</span><strong>{formatBudgetMoney(row.realityAmount, row.currency)}</strong><span className="text-xs text-muted-foreground">/ plán {hasPlan ? formatBudgetMoney(row.planAmount, row.currency) : "—"}</span></div>{hasPlan ? <><div role="progressbar" aria-label={`Utraceno ${percentage} % plánovaného rozpočtu v měně ${row.currency}`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={visualPercentage} className="mt-3 h-2 overflow-hidden rounded-full bg-muted"><div className={overBudget ? "h-full rounded-full bg-amber-300" : "h-full rounded-full bg-primary"} style={{ width: `${visualPercentage}%` }} /></div><p className={overBudget ? "mt-2 text-xs text-amber-200" : "mt-2 text-xs text-muted-foreground"}>{overBudget ? `Překročeno o ${formatBudgetMoney(Math.abs(row.remainingBudget), row.currency)}` : `Zbývá z plánu ${formatBudgetMoney(row.remainingBudget, row.currency)}`}</p></> : <p className="mt-3 text-xs text-muted-foreground">Rozpočet zatím není naplánovaný.</p>}</div><div className="border-t border-border pt-3 text-sm sm:border-t-0 sm:border-l sm:pt-0 sm:pl-4"><p className="text-muted-foreground">Zaplaceno</p><strong className="mt-1 block">{formatBudgetMoney(row.paidAmount, row.currency)}</strong><p className="mt-3 text-muted-foreground">Zbývá zaplatit</p><strong className="mt-1 block">{formatBudgetMoney(row.remainingPayment, row.currency)}</strong></div></div></div>; }
function Payment({ data, tripId }: { data: Overview; tripId: string }) { const item = data.nearestPayment; const href = item && (item.sourceType === "accommodation" || item.sourceType === "transport") ? `/app/trips/${tripId}/${item.sourceType}?edit=${item.sourceId}` : `/app/trips/${tripId}/budget?tab=payments`; const title = data.nearestPaymentOverdue ? "Po splatnosti" : "Další platba"; return <Block href={href} icon={<ReceiptText />} title={title} action="Rozpočet">{item ? <><p className="font-medium">{item.title}</p><p className={data.nearestPaymentOverdue ? "mt-1 text-sm font-semibold text-amber-200" : "mt-1 text-sm text-muted-foreground"}>Zbývá zaplatit {formatBudgetMoney(item.remainingAmount ?? 0, item.currency)} · {item.dueDate ? `splatnost ${formatDateOnly(item.dueDate)}` : "bez termínu"}</p></> : <Empty>Žádná naplánovaná platba.</Empty>}</Block>; }
function Transport({ data, tripId }: { data: Overview; tripId: string }) { const item = data.nearestTransport; return <Block href={`/app/trips/${tripId}/transport`} icon={<Plane />} title="Nejbližší přesun" action="Doprava">{item ? <><p className="font-medium">{item.booking.title}{item.segment.service_number ? ` · ${item.segment.service_number}` : ""}</p><p className="mt-1 text-sm text-muted-foreground">{item.segment.departurePlace?.name ?? "Odjezd"} → {item.segment.arrivalPlace?.name ?? "Příjezd"}</p><p className="text-xs text-muted-foreground">{item.segment.departure_at ? formatTripDateTime(item.segment.departure_at, data.timezone ?? "Europe/Prague") : "Termín není zadaný"}</p></> : <Empty>Zatím žádný budoucí přesun.</Empty>}</Block>; }
function Accommodation({ data, tripId }: { data: Overview; tripId: string }) { const item = data.upcomingAccommodation; return <Block href={`/app/trips/${tripId}/accommodation`} icon={<BedDouble />} title="Ubytování" action="Ubytování">{item ? <><p className="font-medium">{item.name}</p><p className="mt-1 text-sm text-muted-foreground">{formatDateOnly(item.check_in_date)} – {formatDateOnly(item.check_out_date)}{item.check_in_time ? ` · check-in ${item.check_in_time}` : ""}</p></> : <Empty>Zatím není přidané žádné ubytování.</Empty>}</Block>; }
function Tasks({ data, tripId }: { data: Overview; tripId: string }) { return <Block href={`/app/trips/${tripId}/checklist`} icon={<Luggage />} title="Checklist" action="Checklist">{data.openTasks.length ? data.openTasks.map((task) => <p key={task.id} className="border-b border-border py-2 text-sm last:border-0"><span className="font-medium">{task.title}</span>{task.due_date ? <span className="ml-2 text-xs text-muted-foreground">do {formatDateOnly(task.due_date)}</span> : null}</p>) : <Empty>Žádné otevřené úkoly.</Empty>}</Block>; }
function Documents({ data, tripId }: { data: Overview; tripId: string }) { return <Block href={`/app/trips/${tripId}/documents`} icon={<FileText />} title="Dokumenty" action="Dokumenty">{data.document.total ? <p className="text-sm text-muted-foreground">{data.document.total} dokumentů · {data.document.important} důležité · {data.document.offline} označených offline</p> : <Empty>Žádné dokumenty.</Empty>}</Block>; }
function Empty({ children }: { children: React.ReactNode }) { return <p className="text-sm text-muted-foreground">{children}</p>; }
