import { cleanup, fireEvent, render, screen, within } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
vi.mock("./checklist-actions", () => ({ createPackingItem: vi.fn(), createTask: vi.fn(), deletePackingItem: vi.fn(), deleteTask: vi.fn(), setPackingItemPacked: vi.fn(), setTaskCompleted: vi.fn(), updatePackingItem: vi.fn(), updateTask: vi.fn() }));
import { ChecklistDashboard } from "./checklist-dashboard";
import { TaskForm } from "./checklist-form";
import type { ChecklistPackingItem, ChecklistTask } from "./checklist-model";
afterEach(cleanup);

const task = (overrides: Partial<ChecklistTask> = {}): ChecklistTask => ({ assigned_traveler_id: "traveler", category: "payment", created_at: "2027-01-01", created_by: "user", description: null, due_date: "2027-05-15", id: "task", linked_entity_id: null, linked_entity_type: null, priority: "high", status: "todo", title: "Doplatit hotel", travelerName: "Zdeněk", trip_id: "trip", updated_at: "2027-01-01", ...overrides });
const packing: ChecklistPackingItem = { bag_type: "cabin", category: "electronics", created_at: "2027-01-01", created_by: "user", id: "packing", is_packed: false, name: "Adaptér", quantity: 2, traveler_id: "traveler", travelerName: "Zdeněk", trip_id: "trip", updated_at: "2027-01-01" };

describe("checklist UI", () => {
  it("uses the shared optional DatePicker for task due dates and preserves the canonical value", () => {
    const { container } = render(<TaskForm canEdit task={task() as never} travelers={[]} tripId="trip" />);
    expect(screen.getByRole("button", { name: "Termín" })).toBeInTheDocument();
    expect(container.querySelector('input[type="date"]')).not.toBeInTheDocument();
    expect(new FormData(container.querySelector("form")!).get("dueDate")).toBe("2027-05-15");
  });

  it("keeps the task form read-only for viewers", () => {
    render(<TaskForm canEdit={false} task={task() as never} travelers={[]} tripId="trip" />);
    expect(screen.getByRole("button", { name: "Termín" })).toBeDisabled();
  });

  it("renders separate compact summaries and progress for tasks and packing", () => { render(<ChecklistDashboard canEdit currentTravelerId="traveler" packingItems={[packing, { ...packing, id: "packed", is_packed: true, name: "Pas" }]} tasks={[task(), task({ id: "done", status: "completed", title: "Hotovo" })]} tripId="trip" />); const taskSummary = screen.getByLabelText("Souhrn úkolů"); const packingSummary = screen.getByLabelText("Souhrn balení"); expect(taskSummary).toHaveTextContent("1 / 2 hotovo"); expect(taskSummary).toHaveTextContent("1 zbývá"); expect(packingSummary).toHaveTextContent("1 / 2 sbaleno"); expect(packingSummary).toHaveTextContent("1 zbývá"); expect(within(taskSummary).getByRole("progressbar")).toHaveAttribute("aria-valuenow", "1"); expect(within(packingSummary).getByRole("progressbar")).toHaveAttribute("aria-valuenow", "1"); expect(screen.getByText("Elektronika")).toBeInTheDocument(); expect(screen.getByText("1 / 2 sbaleno")).toBeInTheDocument(); expect(screen.getByText("Adaptér × 2")).toBeInTheDocument(); expect(screen.getAllByRole("checkbox")).toHaveLength(4); });
  it("filters completed and my tasks", () => { render(<ChecklistDashboard canEdit currentTravelerId="traveler" packingItems={[]} tasks={[task(), task({ assigned_traveler_id: null, id: "done", status: "completed", title: "Hotovo" })]} tripId="trip" />); const filters = screen.getByRole("group", { name: "Filtr úkolů" }); fireEvent.click(within(filters).getByRole("button", { name: "Hotové" })); expect(screen.queryByText("Doplatit hotel")).not.toBeInTheDocument(); expect(screen.getByRole("heading", { name: "Hotovo" })).toBeInTheDocument(); fireEvent.click(within(filters).getByRole("button", { name: "Moje" })); expect(screen.getByText("Doplatit hotel")).toBeInTheDocument(); expect(screen.queryByRole("heading", { name: "Hotovo" })).not.toBeInTheDocument(); });
  it("hides mutation controls for viewers", () => { render(<ChecklistDashboard canEdit={false} currentTravelerId={null} packingItems={[packing]} tasks={[task()]} tripId="trip" />); expect(screen.queryByRole("link", { name: /upravit/i })).not.toBeInTheDocument(); expect(screen.getAllByRole("checkbox").every((control) => control.hasAttribute("disabled"))).toBe(true); });
  it("filters unpacked, packed and my packing items", () => { render(<ChecklistDashboard canEdit currentTravelerId="traveler" packingItems={[packing, { ...packing, id: "packed", is_packed: true, name: "Pas", traveler_id: null }]} tasks={[]} tripId="trip" />); const filters = screen.getByRole("group", { name: "Filtr balení" }); fireEvent.click(within(filters).getByRole("button", { name: "Sbaleno" })); expect(screen.queryByText("Adaptér × 2")).not.toBeInTheDocument(); expect(screen.getByText("Pas × 2")).toBeInTheDocument(); fireEvent.click(within(filters).getByRole("button", { name: "Moje" })); expect(screen.getByText("Adaptér × 2")).toBeInTheDocument(); expect(screen.queryByText("Pas × 2")).not.toBeInTheDocument(); });
  it("keeps task and packing filters independent", () => { render(<ChecklistDashboard canEdit currentTravelerId="traveler" packingItems={[packing, { ...packing, id: "packed", is_packed: true, name: "Pas" }]} tasks={[task(), task({ id: "done", status: "completed", title: "Hotovo" })]} tripId="trip" />); const taskFilters = screen.getByRole("group", { name: "Filtr úkolů" }); const packingFilters = screen.getByRole("group", { name: "Filtr balení" }); fireEvent.click(within(taskFilters).getByRole("button", { name: "Aktivní" })); fireEvent.click(within(packingFilters).getByRole("button", { name: "Sbaleno" })); expect(within(taskFilters).getByRole("button", { name: "Aktivní" })).toHaveAttribute("aria-pressed", "true"); expect(within(packingFilters).getByRole("button", { name: "Sbaleno" })).toHaveAttribute("aria-pressed", "true"); expect(within(taskFilters).getByRole("button", { name: "Vše" })).toHaveAttribute("aria-pressed", "false"); });
  it("uses desktop columns without the mobile switcher", () => { render(<ChecklistDashboard canEdit currentTravelerId="traveler" packingItems={[packing]} tasks={[task()]} tripId="trip" />); expect(screen.getByRole("tablist", { name: "Část checklistu" })).toHaveClass("md:hidden"); expect(screen.getByRole("region", { name: "Úkoly" })).toHaveClass("md:block"); expect(screen.getByRole("region", { name: "Balení" })).toHaveClass("md:block"); expect(screen.getByRole("region", { name: "Úkoly" }).parentElement).toHaveClass("md:grid-cols-2"); });
  it("switches mobile content and the single mobile action together", () => { render(<ChecklistDashboard canEdit currentTravelerId="traveler" packingItems={[packing]} tasks={[task()]} tripId="trip" />); const tasksTab = screen.getByRole("tab", { name: "Úkoly" }); const packingTab = screen.getByRole("tab", { name: "Balení" }); expect(tasksTab).toHaveAttribute("aria-selected", "true"); expect(screen.getByRole("link", { name: "Přidat úkol" })).toHaveAttribute("href", "/app/trips/trip/checklist?new=task"); fireEvent.click(packingTab); expect(packingTab).toHaveAttribute("aria-selected", "true"); expect(tasksTab).toHaveAttribute("aria-selected", "false"); expect(screen.getByRole("link", { name: "Přidat do balení" })).toHaveAttribute("href", "/app/trips/trip/checklist?new=packing"); });
});
